# Generated by Django 3.2.5 on 2021-07-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20210730_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Skills',
            new_name='skills',
        ),
    ]
