# Generated by Django 3.2.5 on 2021-08-02 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_rename_skills_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('company_start_date', models.DateField(blank=True, null=True)),
                ('company_end_date', models.DateField(blank=True, null=True)),
                ('company_career', models.CharField(blank=True, choices=[('1', 'Staff'), ('2', 'Senior Staff'), ('3', 'Assistant Manager'), ('4', 'Manager'), ('5', 'Senior Manager'), ('6', 'Vice President above'), ('7', 'ETC')], max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('education_status', models.CharField(blank=True, choices=[('1', '졸업'), ('2', '졸업예정'), ('3', '중퇴'), ('4', '휴학'), ('5', '재학')], max_length=100, null=True)),
                ('education_major', models.CharField(blank=True, max_length=100, null=True)),
                ('projects', models.CharField(blank=True, max_length=100, null=True)),
                ('projects_date', models.DateField(blank=True, null=True)),
                ('projects_desc', models.TextField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('license_list', models.CharField(blank=True, max_length=100, null=True)),
                ('license_list_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='member.cvcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
