# Generated by Django 3.2.5 on 2021-08-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_cvcategory_cvitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='options',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cvitem',
            name='company_career',
            field=models.CharField(blank=True, choices=[('1', '사원'), ('2', '주임'), ('3', '대리'), ('4', '과장'), ('5', '차장'), ('6', '부장'), ('7', '임원 이상'), ('8', '기타')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
