# Generated by Django 3.2.5 on 2021-08-11 14:40

import apps.teams.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('essencial', models.CharField(max_length=200)),
                ('plus', models.CharField(max_length=100)),
                ('msg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('manpower', models.IntegerField()),
                ('career', models.CharField(choices=[('1', '경력 무관'), ('2', '2년 미만'), ('3', '5년 미만'), ('4', '10년 미만'), ('5', '10년 이상')], max_length=1)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('short_description', models.TextField(max_length=1024)),
                ('purpose', models.CharField(blank=True, choices=[('1', '창업'), ('2', '취미'), ('3', '사이드프로젝트'), ('4', '스터디'), ('5', 'ETC')], max_length=1, null=True)),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.teams.models.team_img_path)),
                ('team_banner', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.teams.models.team_img_path)),
                ('team_detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='팀장', max_length=30, verbose_name='직책')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='teams.teamorg', verbose_name='parent')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_org', to='teams.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'REGISTERED'), ('2', 'APPROVE'), ('3', 'REJECT')], max_length=1, null=True)),
                ('msg', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_user', to='teams.findmember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='findmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_member', to='teams.team'),
        ),
    ]
