# Generated by Django 3.2.5 on 2021-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamorg',
            name='authority',
            field=models.BooleanField(default=False),
        ),
    ]
