# Generated by Django 3.2.5 on 2021-07-30 11:43

import apps.teams.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_registeredmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.teams.models.team_img_path),
        ),
    ]
