# Generated by Django 3.2.5 on 2021-08-04 05:31

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210803_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
