# Generated by Django 3.2.5 on 2021-08-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20210803_0325'),
        ('teams', '0007_team_team_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(blank=True, null=True, to='member.Profile'),
        ),
    ]
