# Generated by Django 3.2.5 on 2021-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20210803_0325'),
        ('teams', '0008_alter_team_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='member.Profile'),
        ),
    ]
