# Generated by Django 3.2.5 on 2021-08-05 07:19

import apps.teams.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_findmember_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.teams.models.team_img_path),
        ),
    ]
