# Generated by Django 3.2.5 on 2021-08-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_team_team_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredmember',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.findmember'),
        ),
        migrations.AlterField(
            model_name='findmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_member', to='teams.team'),
        ),
    ]
