# Generated by Django 3.2.5 on 2021-08-08 11:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_teamorg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamorg',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='teams.teamorg', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='teamorg',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='teams.team'),
        ),
    ]
