# Generated by Django 3.2.5 on 2021-08-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20210808_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamorg',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='teams.team'),
        ),
    ]
