# Generated by Django 3.2.5 on 2021-08-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_alter_teamorg_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamorg',
            name='team',
        ),
    ]
