# Generated by Django 3.2.5 on 2021-08-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_remove_teamorg_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamorg',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='teams.team'),
        ),
    ]
