# Generated by Django 3.2.5 on 2021-08-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_teamorg_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamorg',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='team_org',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='teams.teamorg', verbose_name='조직도'),
        ),
    ]
