# Generated by Django 3.2.5 on 2021-08-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20210808_0826'),
        ('teams', '0020_auto_20210808_2034'),
    ]

    operations = [
    ]
