# Generated by Django 3.2.5 on 2021-08-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_auto_20210808_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_org',
        ),
        migrations.AddField(
            model_name='teamorg',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
