# Generated by Django 3.2.5 on 2021-08-08 15:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_merge_0013_auto_20210808_0826_0020_auto_20210808_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_org',
            field=models.OneToOneField(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='teams.teamorg', verbose_name='조직도'),
        ),
        migrations.AlterField(
            model_name='teamorg',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='teams.teamorg'),
        ),
    ]
