# Generated by Django 3.2.5 on 2021-08-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20210803_0325'),
        ('teams', '0021_auto_20210809_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(blank=True, related_name='teams', to='member.Profile'),
        ),
        migrations.AlterField(
            model_name='teamorg',
            name='position',
            field=models.CharField(default='팀장', max_length=30, verbose_name='직책'),
        ),
    ]
